#!/bin/bash
# fortisc: Fortran + PyTorch model -> one executable. Usage: fortisc.sh export.py host.f90 out
set -e
EXPORT=$1; HOST=$2; OUT=$3
ROOT=/scratch/taghipouranvari.s/FTORCH/torch-mlir
CUDNN=$(ls -d /scratch/taghipouranvari.s/FTORCH/Fortran-ML-Interface/venv-fortran-ml/lib64/python3.9/site-packages/nvidia/cudnn)
MATH=/shared/EL9/explorer/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/math_libs/12.5
CUDA=/shared/EL9/explorer/nvidia-hpc-sdk/24.7/Linux_x86_64/24.7/cuda/12.5
B=$ROOT/build/bin
W=${FORTIS_WORK:-$ROOT/fortisc_work}; mkdir -p $W
PIC=${FORTIS_JIT_COUNT:+-fPIC}
J() { python3 -c "import json;d=json.load(open('$1'));print($2)"; }

# --- host analysis: call-site shapes and loop context (FIR), loop distribution (HLFIR)
$B/flang -fc1 -emit-fir $HOST -o $W/host.fir
$B/flang -fc1 -emit-hlfir $HOST -o $W/host.hlfir
python3 $ROOT/fortis_hostinfo.py $W/host.fir mlp_forward > $W/hostinfo.json
python3 $ROOT/fortis_alias.py $W/host.hlfir mlp_forward > $W/alias.json
if [ "$(J $W/alias.json "d['ok']")" != "True" ]; then
  echo "fortisc: aliasing ($(J $W/alias.json "'; '.join(d['reasons'])")): loop distribution and boundary disabled"
  export FORTIS_NO_DIST=1
fi
PYTHONPATH=$ROOT python3 $ROOT/fortis_loopdist.py $W/host.hlfir mlp_forward > $W/loop.json 2>/dev/null || echo '{"verdict": "reject", "reason": "slice analysis failed", "lift": null}' > $W/loop.json
LV=$(J $W/loop.json "d['verdict']"); DIS=-; EXPAND=no
if [ "$LV" != "batched" ] && [ -z "$FORTIS_NO_DIST" ]; then
  # general body model: units, expanded call temporaries, fission at HLFIR
  python3 $ROOT/fortis_units.py $W/host.hlfir mlp_forward > $W/units.json
  if [ "$(J $W/units.json "d['verdict']")" = "batched" ]; then cp $W/units.json $W/loop.json; LV=batched; EXPAND=yes; fi
fi
if [ -n "$FORTIS_NO_DIST" ]; then LV=disabled; DIS=disabled; fi
GATHER=no; echo '{"ok": false}' > $W/gather.json
if [ "$LV" = "batched" ] && [ "$EXPAND" = yes ] && [ -z "$FORTIS_NO_GATHER" ]; then
  python3 $ROOT/fortis_gather.py $W/host.hlfir $W/loop.json > $W/gather.json
  if [ "$(J $W/gather.json "d['ok']")" = "True" ]; then GATHER=yes; export FORTIS_GATHER=1; fi
  echo "fortisc: stencil lift $GATHER ($(J $W/gather.json "d['reason'][:120]"))"
fi
# --- run-time extents: the loop count is a run-time value.  Ahead of time, build the distributed host with a
# stub and a jit script; FORTIS_JIT_COUNT=n reruns this script to build the model side for n rows as a .so
RT=$(J $W/loop.json "d.get('verdict') == 'batched' and d.get('batch') is None")
if [ "$RT" = True ] && [ -n "$FORTIS_JIT_COUNT" ]; then
  python3 -c "import json;d=json.load(open('$W/loop.json'));d['batch']=int('$FORTIS_JIT_COUNT');json.dump(d,open('$W/loop.json','w'))"; RT=False
fi
if [ "$RT" = True ]; then
  echo "fortisc: loop count is a run-time value; the model side is specialized at first call"
  python3 $ROOT/fortis_fission_hlfir.py $W/host.hlfir $W/loop.json > $W/host_fissioned.fir
  $B/flang -fc1 -emit-llvm -O3 $W/host_fissioned.fir -o $W/host.ll
  $B/clang -O2 -c $W/host.ll -o $W/host.o
  OUTABS=$(readlink -f $(dirname $OUT))/$(basename $OUT); HOSTABS=$(readlink -f $HOST); EXPABS=$(readlink -f $EXPORT); TAG=$(basename $HOST .f90)
  cat > $OUTABS.jit.sh <<EOJ
#!/bin/bash
# generated by fortisc: build the model side of $HOSTABS for a run-time loop count as a shared object
COUNT=\$1; SO=\$2
cd $(dirname $HOSTABS)
FORTIS_JIT_COUNT=\$COUNT FORTIS_WORK=$ROOT/fortisc_work_jit_$TAG\_\$COUNT bash $ROOT/fortisc.sh $EXPABS $HOSTABS \$SO > \$SO.log 2>&1
EOJ
  $B/clang -O2 -DFORTIS_JIT_SCRIPT="\"$OUTABS.jit.sh\"" -DFORTIS_CACHE_DIR="\"$(dirname $OUTABS)/fortis_cache\"" -DFORTIS_HOST_TAG="\"$TAG\"" -c $ROOT/fortis_stub.c -o $W/stub.o
  $B/flang -O3 $W/host.o $W/stub.o -ldl -o $OUT
  echo "fortisc: host distributed, stub linked, jit script $OUTABS.jit.sh -> $OUT"; exit 0
fi
echo "fortisc: loop verdict $LV ($(J $W/loop.json "d['reason'][:110]"))"
if [ "$LV" = "batched" ]; then export FORTIS_BATCH=$(J $W/loop.json "d['batch']"); else export FORTIS_BATCH=$(J $W/hostinfo.json "d['batch']"); fi
echo "fortisc: call site batch=$FORTIS_BATCH in_loop=$(J $W/hostinfo.json "d['in_loop']")"

# --- whole-array call: the boundary analysis (2-D lifts, layout casts) decides whether the model can take the host's own arrays
BND=no; BNDJ=""
if [ "$LV" != "batched" ] && [ -z "$FORTIS_NO_DIST" ] && [ -z "$FORTIS_NO_BOUNDARY" ]; then
  python3 $ROOT/fortis_lift2d.py $W/host.hlfir mlp_forward > $W/lift2d.json
  if [ "$(J $W/lift2d.json "d['ok']")" = "True" ]; then BND=yes; BNDJ=$W/lift2d.json; fi
  echo "fortisc: boundary $BND ($(J $W/lift2d.json "d.get('reject') or ('drop %d host statements, pre=%s post=%s' % (len(d['drop']), (d['pre'] or {}).get('globals'), (d['post'] or {}).get('globals')))"))"
fi

# --- model export at the host's batch; lifted host expressions are merged around it
if [[ "$EXPORT" == *.mlir ]]; then cp $EXPORT $W/model_linalg.mlir; else source ~/venvs/tmlir/bin/activate && python $EXPORT > $W/model_linalg.mlir && deactivate; fi
if [ "$LV" = "batched" ] && [ "$(J $W/loop.json "d['lift'] is not None")" = "True" ]; then
  python3 -c "import json;json.dump(json.load(open('$W/loop.json'))['lift'], open('$W/lift.json','w'))"
  python3 $ROOT/fortis_hostlift.py --prologue $W/lift.json $W/model_linalg.mlir > $W/model_lifted.mlir
  $B/mlir-opt $W/model_lifted.mlir -inline -symbol-dce -o $W/model_linalg.mlir
elif [ "$BND" = yes ]; then
  python3 $ROOT/fortis_emit2d.py $W/lift2d.json $W/model_linalg.mlir > $W/model_lifted.mlir
  $B/mlir-opt $W/model_lifted.mlir -inline -symbol-dce -o $W/model_linalg.mlir
fi

# --- the contract: host facts become one attribute on the entry function
python3 $ROOT/fortis_hostattr.py $W/model_linalg.mlir $W/hostinfo.json $W/loop.json $DIS $BNDJ > $W/model_annot.mlir
python3 $ROOT/fortis_outline.py $W/model_annot.mlir $W

$B/mlir-opt $W/model_args.mlir -linalg-generalize-named-ops -o $W/m1.mlir
$ROOT/fortis-pass/build/fortis-opt $W/m1.mlir -fortis-fold-transpose -o $W/m2a.mlir
$B/mlir-opt $W/m2a.mlir -canonicalize -cse -o $W/m2.mlir
$B/mlir-opt $W/m2.mlir -one-shot-bufferize="bufferize-function-boundaries function-boundary-type-conversion=identity-layout-map" -buffer-results-to-out-params -o $W/m3.mlir
$ROOT/fortis-pass/build/fortis-opt $W/m3.mlir -fortis-fuse -fortis-host-decide -o $W/m4.mlir
$B/mlir-opt $W/m4.mlir -gpu-lower-to-nvvm-pipeline="cubin-chip=sm_70 cubin-format=fatbin" -o $W/m5.mlir
sed -i 's/@malloc/@fortis_alloc/g; s/@free/@fortis_free/g' $W/m5.mlir
$B/mlir-translate $W/m5.mlir --mlir-to-llvmir -o $W/model.ll
$B/clang -O2 $PIC -c $W/model.ll -o $W/model.o

$B/mlir-translate $W/weights.mlir --mlir-to-llvmir -o $W/weights.ll
$B/clang -O2 $PIC -c $W/weights.ll -o $W/weights.o

# --- shim and host object from the attributes on the fused module
python3 $ROOT/fortis_shim.py $W/m4.mlir $W/outline.json $W
$B/clang -O2 $PIC -I$CUDA/include -c $W/shim.c -o $W/shim.o
$B/clang -O2 $PIC -I$CUDA/include -I$MATH/include -I$CUDNN/include -c $ROOT/fortis_rt.c -o $W/fortis_rt.o && $CUDA/bin/nvcc -O2 -arch=sm_70 -Xcompiler -fPIC -I$CUDA/include -I$MATH/include -c $ROOT/fortis_fft.cu -o $W/fortis_fft.o
if [ -n "$FORTIS_JIT_COUNT" ]; then
  # jit mode: the host is already built; link the model side as a shared object for the stub to load
  $B/clang -shared -o $OUT $W/model.o $W/shim.o $W/weights.o $W/fortis_rt.o $W/fortis_fft.o \
    -L$ROOT/build/lib -lmlir_cuda_runtime -L$CUDA/lib64 -lcudart -L$MATH/lib64 -lcublas -Wl,-rpath,$MATH/lib64 $CUDNN/lib/libcudnn.so.8 -Wl,-rpath,$CUDNN/lib -lcufft \
    -Wl,-rpath,$ROOT/build/lib -Wl,-rpath,$CUDA/lib64
  echo "fortisc: kernels=$(grep -c gpu.launch_func $W/m4.mlir) library calls=$(grep -c 'call @fortis_' $W/m4.mlir || true) -> $OUT (specialized for $FORTIS_JIT_COUNT rows)"; exit 0
elif [ "$LV" = "batched" ] && [ "$EXPAND" = yes ]; then
  # fission at HLFIR with the call temporaries expanded across the batch
  python3 $ROOT/fortis_fission_hlfir.py $W/host.hlfir $W/loop.json $W/gather.json > $W/host_fissioned.fir
  $B/flang -fc1 -emit-llvm -O3 $W/host_fissioned.fir -o $W/host.ll
  GOBJ=""
  if [ "$GATHER" = yes ]; then
    for sym in $(J $W/gather.json "' '.join(a['name'] for a in d['arrays'])"); do sed -i "s/^@$sym = internal global/@$sym = global/" $W/host.ll; done
    python3 $ROOT/fortis_gather_emit.py $W/gather.json $W/loop.json > $W/gather.cu
    $CUDA/bin/nvcc -O2 -arch=sm_70 -fmad=false -Xcompiler -fPIC -I$CUDA/include -c $W/gather.cu -o $W/gather.o; GOBJ=$W/gather.o
  fi
  $B/clang -O2 -c $W/host.ll -o $W/host.o; HOSTOBJ="$W/host.o $GOBJ"
elif [ "$LV" = "batched" ]; then
  # loop fission at FIR: pre-loop, one batched call, post-loop; Lift statements move into the model
  python3 $ROOT/fortis_fission.py $W/host.fir $W/loop.json mlp_forward > $W/host_fissioned.fir
  $B/flang -fc1 -emit-llvm -O3 $W/host_fissioned.fir -o $W/host.ll
  for sym in $(J $W/loop.json "' '.join([g['sym'] for g in (d['lift'] or {}).get('globals', [])])"); do
    sed -i "s/^@$sym = internal global/@$sym = global/" $W/host.ll; done
  $B/clang -O2 -c $W/host.ll -o $W/host.o; HOSTOBJ=$W/host.o
elif [ "$BND" = yes ]; then
  # boundary at HLFIR: lifted nests and layout casts removed, the call takes the host's own arrays
  python3 $ROOT/fortis_boundary.py $W/host.hlfir $W/lift2d.json > $W/host_boundary.fir
  $B/flang -fc1 -emit-llvm -O3 $W/host_boundary.fir -o $W/host.ll
  for sym in $(J $W/lift2d.json "' '.join((d['pre'] or {}).get('globals', []) + (d['post'] or {}).get('globals', []))"); do
    sed -i "s/^@$sym = internal global/@$sym = global/" $W/host.ll; done
  $B/clang -O2 -c $W/host.ll -o $W/host.o; HOSTOBJ=$W/host.o
else HOSTOBJ=$HOST; fi
$B/flang -O3 $HOSTOBJ $W/model.o $W/shim.o $W/weights.o $W/fortis_rt.o \
  -L$ROOT/build/lib -lmlir_cuda_runtime -L$CUDA/lib64 -lcudart -L$MATH/lib64 -lcublas -Wl,-rpath,$MATH/lib64 $CUDNN/lib/libcudnn.so.8 -Wl,-rpath,$CUDNN/lib -lcufft $W/fortis_fft.o \
  -Wl,-rpath,$ROOT/build/lib -Wl,-rpath,$CUDA/lib64 -o $OUT
echo "fortisc: kernels=$(grep -c gpu.launch_func $W/m4.mlir) library calls=$(grep -c 'call @fortis_' $W/m4.mlir || true) -> $OUT"
